In [1]:
import sys
sys.path.append("/Users/callista/Documents/MATLAB/projects/ColorCorrection/reconstruction/Zhang/Denoiser_Reconstruction/matlabPythonConversions")
from imVecConvert import ImToVec, VecToIm, CalFormatToVec, VecToCalFormat, ImToCalFormat, CalFormatToIm

## VECTOR TO IMAGE AND IMAGE TO VECTOR

In [2]:
# BELOW ARE TESTS TO MAKE SURE THAT MY IMAGE TO VECTOR / VECTOR TO IMAGE, ETC WORKS:
import torch
# Make a tiny test image with easy-to-track values
# Shape is (3, H, W) = (3, 2, 3)
x_image = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6]],

    [[10, 20, 30],
     [40, 50, 60]],

    [[100, 200, 300],
     [400, 500, 600]]
], dtype=torch.float32)

print("Original image:")
print(x_image)
print("shape:", x_image.shape)

# Convert image to vector
x_vec = ImToVec(x_image)

print("\nVectorized image:")
print(x_vec)
print("shape:", x_vec.shape)

# Convert vector back to image
x_image_recovered = VecToIm(x_vec, (2, 3, 3))

print("\nRecovered image:")
print(x_image_recovered)
print("shape:", x_image_recovered.shape)

# Check exact equality
print("\nDoes VecToImage(ImageToVec(x_image)) recover the original?")
print(torch.equal(x_image, x_image_recovered))


Original image:
tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],

        [[ 10.,  20.,  30.],
         [ 40.,  50.,  60.]],

        [[100., 200., 300.],
         [400., 500., 600.]]])
shape: torch.Size([3, 2, 3])

Vectorized image:
tensor([  1.,   4.,   2.,   5.,   3.,   6.,  10.,  40.,  20.,  50.,  30.,  60.,
        100., 400., 200., 500., 300., 600.])
shape: torch.Size([18])

Recovered image:
tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],

        [[ 10.,  20.,  30.],
         [ 40.,  50.,  60.]],

        [[100., 200., 300.],
         [400., 500., 600.]]])
shape: torch.Size([3, 2, 3])

Does VecToImage(ImageToVec(x_image)) recover the original?
True


## IMAFE TO CAL FORMAT AND CAL FORMAT TO IMAGE

In [3]:
import torch

# Make a tiny test image with easy-to-track values
# Shape is (3, H, W) = (3, 2, 3)
x_image = torch.tensor([
    [[1, 2, 3],
     [4, 5, 6]],

    [[10, 20, 30],
     [40, 50, 60]],

    [[100, 200, 300],
     [400, 500, 600]]
], dtype=torch.float32)

print("Original image:")
print(x_image)
print("shape:", x_image.shape)

# Convert image to CalFormat
# shape changes from (3, H, W) to (3, N), where N = H*W
cal_format = ImToCalFormat(x_image)

print("\nCalFormat from image:")
print(cal_format)
print("shape:", cal_format.shape)

# Convert CalFormat back to image
# shape changes from (3, N) back to (3, H, W)
x_image_recovered = CalFormatToIm(cal_format, (2, 3, 3))

print("\nRecovered image from CalFormat:")
print(x_image_recovered)
print("shape:", x_image_recovered.shape)

# # Check exact equality
# print("\nDoes CalFormatToIm(ImToCalFormat(x_image)) recover the original?")
# print(torch.equal(x_image, x_image_recovered))


Original image:
tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],

        [[ 10.,  20.,  30.],
         [ 40.,  50.,  60.]],

        [[100., 200., 300.],
         [400., 500., 600.]]])
shape: torch.Size([3, 2, 3])

CalFormat from image:
tensor([[  1.,   4.,   2.,   5.,   3.,   6.],
        [ 10.,  40.,  20.,  50.,  30.,  60.],
        [100., 400., 200., 500., 300., 600.]])
shape: torch.Size([3, 6])

Recovered image from CalFormat:
tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],

        [[ 10.,  20.,  30.],
         [ 40.,  50.,  60.]],

        [[100., 200., 300.],
         [400., 500., 600.]]])
shape: torch.Size([3, 2, 3])


## CAL FORMAT TO VECTOR AND VECTOR TO CAL FORMAT:

In [ ]:
import torch

# Make a tiny test CalFormat matrix with easy-to-track values
# Shape is (3, N) = (3, 6)
# Each column is one pixel in MATLAB image order
cal_format = torch.tensor([
    [1, 4, 2, 5, 3, 6],
    [10, 40, 20, 50, 30, 60],
    [100, 400, 200, 500, 300, 600]
], dtype=torch.float32)

print("Original CalFormat:")
print(cal_format)
print("shape:", cal_format.shape)

# Convert CalFormat to vector
# shape changes from (3, N) to (3*N,)
x_vec = CalFormatToVec(cal_format)

print("\nVector from CalFormat:")
print(x_vec)
print("shape:", x_vec.shape)

# Convert vector back to CalFormat
# shape changes from (3*N,) back to (3, N)
cal_format_recovered = VecToCalFormat(x_vec, (3, 6))

print("\nRecovered CalFormat from vector:")
print(cal_format_recovered)
print("shape:", cal_format_recovered.shape)

# Check exact equality
print("\nDoes VecToCalFormat(CalFormatToVec(cal_format)) recover the original?")
print(torch.equal(cal_format, cal_format_recovered))
